### ISSUE TITLE
NFS: World Support

### ISSUE THREAD

**Issue by berkay2578** [DennisStanistan/NFSScript#1]
Please tag as Request and Improvement, not a bug report.

So I need to add nfs world to the supported titles but since source of the NFSScriptLoader isn't publicly available I thought I would post here. (Your contact info isn't publicly available) I don't want to decompile your work because I respect people's works. Any chance you could upload it?

**Comment by DennisStanistan** [comment]
I want to further improve NFSScriptLoader before I'll release it's source code to the public however I'll be glad to send the source code of NFSScriptLoader to contributors that want to support more NFS games. Please send me an e-mail at dennisstanistan@gmail.com so I can send you it! 👍

**Comment by berkay2578** [comment]
Sent, thanks!
