### ISSUE TITLE
Carbon.UI.ShowScreenTextMessage crashes the game

### ISSUE THREAD

**Issue by DennisStanistan** [DennisStanistan/NFSScript#10]
Carbon.UI.ShowScreenTextMessage crashes the game and I am clueless. A lot of sleepless nights are ahead due to this.

**Comment by DennisStanistan** [comment]
It's definitely 0x0065C090
Part from Xan's code:
```c
int ShowScreenMessage(char* const message, int type, unsigned char priority)
{
	msg = message;
	typ = type;
	pri = priority;
	_asm
	{
		call 0x0065C090
	}
	return 0;
}
```

**Comment by DennisStanistan** [comment]
Well I managed to get the code caving work but now there is one problem.

```c#
        /// <summary>
        /// Shows a screen text message on the HUD.
        /// </summary>
        /// <param name="message"></param>
        public static void TestShowScreenTextMessage(string message)
        {
            // Change the error message to the message we want to output.
            _setErrorMsgString(message);
            // Code caving for the parameters required
            int addr = _ASM.InjectForAddress(new byte[] { 0x6A, 0x03, 0x6A, 0x02, 0x6A, 0x01, 0x68, 0xDB, 0x3E, 0xB8, 0x8A, 0x6A, 0x00, 0x68, 0xE2, 0x99, 0x9D, 0x00, 0xE9, 0xFD, 0xC0, 0x65, 0x00 }, memory.GetMainProcess().Handle).ToInt32();
            // Show the address of the injected asm bytes.
            Log.Print("ADDR", addr.ToString("X"));
            // Make a jump to the address of the injected asm bytes from 0x0065C0F3
            // Which is the cave exit.
            ASM.MakeJMPAt(0x0065C0F3, addr);
            // Call the function
            Function.Call(SHOW_SCREEN_TEXT_MESSAGE);
        }
```
The caving works fine and well however the game crashes as soon as I call SHOW_SCREEN_TEXT_MESSAGE which is strange because calling SHOW_SCREEN_TEXT_MESSAGE worked before with or without parameters.

**Comment by berkay2578** [comment]
I don't get the final `jmp 0x65c114` it leads to middle of an opcode for me.
```
;65C111
mov fs:[00000000],ecx
;65C114
add [eax],al
add [eax],al
```
Is this intentional?

**Comment by DennisStanistan** [comment]
> Is this intentional?

According to Xan, yes.
He wrote the screen message code in C++
Here's the code:
http://stanistan.ga/my/code.php?id=5bda8b9e

I tried to port it to NFSScript but no success so far.

**Comment by berkay2578** [comment]
NFSC.exe+71054 crashes the game, something XORs the edx register. I'll take a look now.

**Comment by DennisStanistan** [comment]
>EDIT: His code jumps to 65C101, the one that sets up stuff for 67C290, I think you missed that.

My assembly parser messed up and converted jmp 0x065C101 to jmp 0x65c114.

The code is now this:
```c#
      /// <summary>
        /// Shows a screen text message on the HUD.
        /// </summary>
        /// <param name="message"></param>
        public static void ShowScreenTextMessage(string message)
        {
            _setErrorMsgString(message);
            ASMBuilder asm = new ASMBuilder();
            asm.Push(0x3);
            asm.Push(0x2);
            asm.Push(0x1);
            asm.Push(0x8ab83edb);
            asm.Push(0x0);
            asm.Push(0x9d99e2);
            asm.Jmp(0x65C101);
            int addr = _ASM.InjectForAddress(asm.ToArray(), memory.GetMainProcess().Handle).ToInt32();
            Log.Print("ADDR", addr.ToString("X"));
            ASM.MakeJMPAt(0x0065C0F3, addr);
            Function.Call(true, SHOW_SCREEN_TEXT_MESSAGE);
        }
```

And... it's still crashes.

**Comment by berkay2578** [comment]
Even just changing the value that is pushed into the edx register crashes the game: 0x745062C4 (don't know if this is static). I think I'll rewrite the code instead, as even a carbon copy of his code crashes the game.

**Comment by DennisStanistan** [comment]
Okay so remember the argument ```int a1``` from sub_65C090? 
That's the address to the string.

This works perfectly fine:
```c#
_setErrorMsgString(message);
Function.Call(SHOW_SCREEN_TEXT_MESSAGE, message);
```

However when using code caving to allow us to customize the function:
```c#
            _setErrorMsgString(message);
            ASMBuilder asm = new ASMBuilder();
            asm.Push(0x3);
            asm.Push(0x2);
            asm.Push(0x1);
            asm.Push(0x8ab83edb);
            asm.Push(0x0);
            asm.Push(0x9d99e2);
            asm.Jmp(0x65C101);
            int addr = _ASM.InjectForAddress(asm.ToArray(), memory.GetMainProcess().Handle).ToInt32();
            ASM.MakeJMPAt(0x0065C0F3, addr);
            ASMBuilder b = new ASMBuilder();

            Function.Call(SHOW_SCREEN_TEXT_MESSAGE, message);
```
It crashes the game, when I opened the Visual Studio debugger (I know it's shit) it said that the was an access violation at an address that is a few addresses ahead of where the code cave usually allocates itself. 

For example: If the code cave was allocated on 0xB510000 and then I call the function, Visual Studio screams that there's an access violation reading location 0x0BB7C095.
```
 Unhandled exception at 0x0BB7C095 in NFSC.exe: 0xC0000005: Access violation reading location 0x0BB7C095.
```

**Comment by berkay2578** [comment]
I've hooked the beginning of 67C290, these are not _actual_ functions, they seem like static functions as the compiler would save esp at the beginning of them if they were normal functions. Anyways, after hooking the beginning, you can change stuff through the stack, esp+8->esp+1C. the second paremeter is the address to the string, rest you can understand.

**Comment by DennisStanistan** [comment]
Xan figured 67C290, it works.
The new code for `Carbon.UI.ShowScreenTextMessage` is this:
```c#
        /// <summary>
        /// Shows a screen text message on the HUD.
        /// </summary>
        /// <param name="message"></param>
        public static void ShowScreenTextMessage(string message)
        {
            _setErrorMsgString(message);
            IntPtr eventAddress = _ASM.InjectForAddress(new byte[] { 0x24 }, memory.ProcessHandle);
            ASMBuilder asm = new ASMBuilder();

            asm.MovECX((uint)eventAddress.ToInt32());
            asm.Push(0x3); // priority
            asm.Push(0x2); // location
            asm.Push(0x1); // mode
            asm.Push(0x8ab83edb); // type
            asm.Push(0x0); // unknown
            asm.Push(Addrs.UIAddrs.STATIC_ERROR_ALLOCATED_MSG); // mesage
            asm.Push(0x0); // unknown
            asm.MovEAX(EFLASHER_GENERIC); // sub_67C290
            asm.CallEAX();

            asm.Return();
            _ASM.Call(asm.ToArray(), memory.ProcessHandle);
        }
```

Thanks for letting Xan & I know that sub_67C290 exists.
