### ISSUE TITLE
Code caving for more functionality

### ISSUE THREAD

**Issue by DennisStanistan** [DennisStanistan/NFSScript#11]
It's time for me to figure out a way to inject code caves using C# for more functionality such as colorful screen text messages.

**Comment by berkay2578** [comment]
You either:
1. Create a 8086 assembler parser from string to bytes
2. Write some logic that understands call/jmp near/far
3. Make parser understand what `[dummy]` means

MemorySharp has an Assembler class that does all these, however introducing it would mean complete removal of `GameMemory` and thus the `VAMemory' and the `GMemory`, not to mention it would also mean another middleman between the process<->NFScript.

Or, you do stuff a little dirty and:
1. Write base bytes to the cave; i.e.:
```
// Example, for ->
push ecx
mov ecx, [myVal]
mov eax, ecx
pop ecx
jmp jumpAddress
// -> you write "\x51\x8B\x0D\x00\x00\x00\x00\x89\xC8\x59\xE9\x00\x00\x00\x00"
```
2. Replace the dummy 0x0 addresses with actual addresses

If you ask me, I'd take the second option almost always (for a project like this). I use it personally, and have never felt the need for a huge overhead like MemorySharp:
```
byte[] caveBytes = new byte[] { 0x53, 0x8B, 0x1D, 0x00, 0x00, 0x00, 0x00, 0x89, 0x59, 0x0C, 0x8B, 0x1D, 0x00, 0x00, 0x00, 0x00, 0x89, 0x59, 0x2C, 0x8B, 0x1D, 0x00, 0x00, 0x00, 0x00, 0x89, 0x59, 0x58, 0x5B, 0xD9, 0x41, 0x58, 0xD9, 0x58, 0x08, 0xE9, 0x00, 0x00, 0x00, 0x00 };

AllocatedMemory allocMem = memory.Allocate(128);
UInt32 localValueCount = 3;
IntPtr localVal1 = allocMem.BaseAddress;
IntPtr localVal2 = allocMem.BaseAddress + 0x4;
IntPtr localVal3 = allocMem.BaseAddress + 0x8;
// ...
UInt32 cavePadding = localValueCount * 0x4;
IntPtr caveStart = allocMem.BaseAddress + cavePadding;

memory.Write(localVal1, val1, false);
memory.Write(localVal2, val2, false);
memory.Write(localVal3, val3, false);
// ...
memory.Write(caveStart, caveBytes, false);

allocMem.Write(cavePadding + 0x3, localVal1); // mov ebx,[localVal1]
allocMem.Write(cavePadding + 0xC, localVal2); // mov ebx,[localVal2]
allocMem.Write(cavePadding + 0x15, localVal3); // mov ebx,[localVal3]

Int32 addrOriginalCode = 0xDEADBEEF;
Int32 jmpToCave = caveStart.ToInt32() - addrOriginalCode - 0x5;
Int32 jmpToOriginalCode = (addrOriginalCode.ToInt32() + 0x5) - (caveStart.ToInt32() + 0x28);

allocMem.Write(cavePadding + 0x24, jmpToOriginalCode);
// Cave Finalized.

memory.Write<byte>(addrOriginalCode, 0xE9);
memory.Write(addrOriginalCode + 0x1, jmpToCave);
```

Let me know if you see nothing wrong with the second option, I can write a generic function for it. (What is it with me and generic functions...)

**Comment by DennisStanistan** [comment]
> Let me know if you see nothing wrong with the second option, I can write a generic function for it. (What is it with me and generic functions...)

I see nothing wrong with the second option.

**Comment by DennisStanistan** [comment]
I added a function called `_ASM.InjectForAddress` which writes byte codes to an address and then returns an IntPtr which is the address and the use `ASM.MakeJMPAt` to do the code caving.

```c#
int addr = _ASM.InjectForAddress(new byte[] { 0x6A, 0x03, 0x6A, 0x02, 0x6A, 0x01, 0x68, 0xDB, 0x3E, 0xB8, 0x8A, 0x6A, 0x00, 0x68, 0xE2, 0x99, 0x9D, 0x00, 0xE9, 0xFD, 0xC0, 0x65, 0x00 }, memory.GetMainProcess().Handle).ToInt32();
ASM.MakeJMPAt(0x0065C0F3, addr);
```
This is an example from the non-functional `Carbon.UI.ShowScreenTextMessage(string message)`.
