### ISSUE TITLE
NFSScript development stopped. (UPDATE)

### ISSUE THREAD

**Issue by DennisStanistan** [DennisStanistan/NFSScript#18]
I am no longer going to work on NFSScript, I've lost all motivation and I pushed all the source code including the loader, feel free to do whatever you want with it.

I am going to delete this project from Github in 30 days from now.

**EDIT**: Due to many requests from the community members of NFS, I won't delete the project from Github and instead I will let other people take charge of the project.

**Comment by ArtyomIsFlash** [comment]
rip

**Comment by Zireael07** [comment]
I understand losing motivation, but please don't delete the project. The project should stay whether you work on it or not (and you don't have to work on it)

**Comment by DennisStanistan** [comment]
The decision has been made though NFSScript won't go anywhere even after I delete it from Github since the source code is out there for everyone to download. I'll let someone else pick up the pieces.

In the meanwhile I am going to focus on more important projects.

**Comment by berkay2578** [comment]
Dennis is adding collaborators, this ain't dying, yet.
